from pathlib import Path

path = Path("tests/unit/test_rise_visual_speed.py")
text = path.read_text(encoding="utf-8")
old = '''    def test_header_speed_is_applied_after_launch_speed(self) -> None:\n        document = parse_bytes(make_normal_nx20(), source="NM.NX")\n        document = InsertMetadata.from_ints(\n            document.stable_id, 1111, _f32_bits(1.5)\n        ).apply(document)\n        snapshot = create_preview_snapshot(document)\n        stream = build_event_stream(snapshot, resolve_route(snapshot, RoutePolicy.MANUAL))\n\n        self.assertAlmostEqual(stream.modifier_for_launch_speed(4.0).speed, 6.0)\n\n        document = InsertMetadata.from_ints(\n            document.stable_id, 0, _f32_bits(12.0)\n        ).apply(document)\n        snapshot = create_preview_snapshot(document)\n        stream = build_event_stream(snapshot, resolve_route(snapshot, RoutePolicy.MANUAL))\n        # ID 0 decodes 12 -> 3 and replaces the launch speed before 1111 x1.5.\n        self.assertAlmostEqual(stream.modifier_for_launch_speed(9.0).speed, 4.5)\n'''
new = '''    def test_legacy_header_speed_is_applied_after_launch_speed(self) -> None:\n        document = parse_bytes(make_normal_nx20(), source="NM.NX")\n        document = InsertMetadata.from_ints(\n            document.stable_id, 1111, _f32_bits(1.5)\n        ).apply(document)\n        snapshot = create_preview_snapshot(document)\n        stream = build_event_stream(snapshot, resolve_route(snapshot, RoutePolicy.MANUAL))\n\n        self.assertAlmostEqual(stream.modifier_for_launch_speed(4.0).speed, 6.0)\n\n        document = InsertMetadata.from_ints(\n            document.stable_id, 0, _f32_bits(12.0)\n        ).apply(document)\n        snapshot = create_preview_snapshot(document)\n        stream = build_event_stream(snapshot, resolve_route(snapshot, RoutePolicy.MANUAL))\n        # NXA/Fiesta/Prime Header 0 is the final float multiplier. It replaces\n        # the dropdown selection before Header 1111 applies its x1.5 factor.\n        self.assertAlmostEqual(stream.modifier_for_launch_speed(9.0).speed, 18.0)\n'''
if old not in text:
    raise SystemExit("legacy Header speed test fragment not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
