from pathlib import Path

preview = Path('src/stepnx/gui/preview_widget.py')
text = preview.read_text(encoding='utf-8')

old = 'from stepnx.authoring.noteskin import LocalNoteskinPack, PngAtlas\n'
new = 'from stepnx.authoring.noteskin import LocalNoteskinPack, PngAtlas, hold_atlas_plan\n'
assert old in text
text = text.replace(old, new, 1)

old = '        self._noteskin_pack: LocalNoteskinPack | None = None\n        self._pixmaps: dict[str, QPixmap] = {}\n'
new = '        self._noteskin_pack: LocalNoteskinPack | None = None\n        self._pixmaps: dict[str, QPixmap] = {}\n        self._hold_terminal_pixmaps: dict[tuple[str, int, int, bool], QPixmap] = {}\n'
assert old in text
text = text.replace(old, new, 1)

old = '        self._noteskin_pack = pack\n        self._pixmaps.clear()\n'
new = '        self._noteskin_pack = pack\n        self._pixmaps.clear()\n        self._hold_terminal_pixmaps.clear()\n'
assert old in text
text = text.replace(old, new, 1)

needle = '    def _draw_asset(self, painter: QPainter, event: PreviewEvent, rect: QRectF) -> bool:\n'
assert needle in text
helper = '''    def _hold_terminal_pixmap(\n        self,\n        pixmap: QPixmap,\n        atlas: PngAtlas,\n        column: int,\n        row: int,\n        *,\n        shaft_above: bool,\n    ) -> QPixmap:\n        \"\"\"Compose one hold terminal with the native repeatable shaft strip.\"\"\"\n\n        key = (str(atlas.path), int(column), int(row), bool(shaft_above))\n        cached = self._hold_terminal_pixmaps.get(key)\n        if cached is not None:\n            return cached\n\n        tile_x, tile_y, tile_width, tile_height = atlas.tile(column, row)\n        source = pixmap.toImage()\n        terminal = source.copy(tile_x, tile_y, tile_width, tile_height)\n        shaft_height = min(8, tile_height)\n        shaft_source = source.copy(\n            tile_x, atlas.tile(column, 0)[1], tile_width, shaft_height\n        )\n        shaft = QImage(tile_width, tile_height, QImage.Format.Format_ARGB32)\n        shaft.fill(Qt.GlobalColor.transparent)\n        shaft_painter = QPainter(shaft)\n        try:\n            shaft_painter.drawImage(\n                QRectF(0, 0, tile_width, tile_height),\n                shaft_source,\n                QRectF(0, 0, shaft_source.width(), shaft_source.height()),\n            )\n        finally:\n            shaft_painter.end()\n\n        # The arrow/tail silhouette is diagonal. Clip the repeated shaft per\n        # source column rather than using one global top/bottom bound. This is\n        # the same composition used by the authoring timeline and prevents the\n        # complete row-0 tile from becoming a 96px plate on tiny/zero-scroll\n        # holds.\n        for x in range(tile_width):\n            search_start = shaft_height if shaft_above and row == 0 else 0\n            opaque_rows = [\n                y\n                for y in range(search_start, tile_height)\n                if terminal.pixelColor(x, y).alpha() > 0\n            ]\n            if not opaque_rows:\n                for y in range(tile_height):\n                    shaft.setPixelColor(x, y, Qt.GlobalColor.transparent)\n                continue\n            boundary = min(opaque_rows) if shaft_above else max(opaque_rows)\n            erase_rows = (\n                range(boundary, tile_height)\n                if shaft_above\n                else range(boundary + 1)\n            )\n            for y in erase_rows:\n                shaft.setPixelColor(x, y, Qt.GlobalColor.transparent)\n\n        composite = QImage(tile_width, tile_height, QImage.Format.Format_ARGB32)\n        composite.fill(Qt.GlobalColor.transparent)\n        composite_painter = QPainter(composite)\n        try:\n            composite_painter.drawImage(0, 0, shaft)\n            composite_painter.drawImage(0, 0, terminal)\n        finally:\n            composite_painter.end()\n        result = QPixmap.fromImage(composite)\n        self._hold_terminal_pixmaps[key] = result\n        return result\n\n'''
text = text.replace(needle, helper + needle, 1)

old = '''        if note_type in (0x3, 0x7, 0xB, 0xF):\n            bank = pack.bank(subtype)\n            if bank is None:\n                return False\n            frame = int(max(0.0, self._chart_time_ms) // 80) % len(bank.animation)\n            atlas = bank.animation[frame]\n            row = {\n                0x3: 2 if (event.raw[0] & 0x60) == 0x20 else 1,\n                0x7: 1,\n                0xB: 0,\n                0xF: 0,\n            }[note_type]\n            return self._draw_atlas(painter, atlas, atlas_lane, row, rect)\n'''
new = '''        if note_type in (0x3, 0x7, 0xB, 0xF):\n            bank = pack.bank(subtype)\n            if bank is None:\n                return False\n            frame = int(max(0.0, self._chart_time_ms) // 80) % len(bank.animation)\n            atlas = bank.animation[frame]\n            if note_type == 0x3:\n                row = 2 if (event.raw[0] & 0x60) == 0x20 else 1\n                return self._draw_atlas(painter, atlas, atlas_lane, row, rect)\n\n            plan = hold_atlas_plan(note_type)\n            pixmap = self._pixmap(atlas)\n            if pixmap is None:\n                return False\n            tile_x, tile_y, tile_width, tile_height = atlas.tile(atlas_lane, 0)\n            body_source = QRectF(\n                tile_x, tile_y, tile_width, min(8, tile_height)\n            )\n            if plan.shaft_above_terminal or plan.shaft_below_terminal:\n                assert plan.terminal_row is not None\n                terminal = self._hold_terminal_pixmap(\n                    pixmap,\n                    atlas,\n                    atlas_lane,\n                    plan.terminal_row,\n                    shaft_above=plan.shaft_above_terminal,\n                )\n                painter.drawPixmap(rect, terminal, QRectF(terminal.rect()))\n                return True\n            if plan.terminal_row is not None:\n                return self._draw_atlas(\n                    painter, atlas, atlas_lane, plan.terminal_row, rect\n                )\n            painter.drawPixmap(rect, pixmap, body_source)\n            return plan.repeat_shaft\n'''
assert old in text
text = text.replace(old, new, 1)

old = '''    @staticmethod\n    def _hold_shaft_height(\n        y1: float,\n        y2: float,\n        rendered_note_size: float,\n        *,\n        head_terminal_visible: bool,\n        tail_terminal_visible: bool,\n    ) -> float:\n        span = abs(float(y2) - float(y1))\n        # Subpixel endpoint noise must not manufacture a visible long body.\n        if span <= 0.5:\n            return 0.0\n        # When both terminal quads are still present, there is no exposed shaft\n        # until their screen-space silhouettes stop overlapping.\n        if (\n            head_terminal_visible\n            and tail_terminal_visible\n            and span <= max(1.0, float(rendered_note_size))\n        ):\n            return 0.0\n        return span\n'''
new = '''    @staticmethod\n    def _hold_shaft_geometry(\n        y1: float,\n        y2: float,\n        rendered_note_size: float,\n        *,\n        head_terminal_visible: bool,\n        tail_terminal_visible: bool,\n    ) -> tuple[float, float]:\n        first = float(y1)\n        second = float(y2)\n        span = abs(second - first)\n        if span <= 0.5:\n            return min(first, second), 0.0\n\n        direction = 1.0 if second >= first else -1.0\n        half_terminal = max(0.0, float(rendered_note_size)) / 2.0\n        exposed_first = first + direction * (\n            half_terminal if head_terminal_visible else 0.0\n        )\n        exposed_second = second - direction * (\n            half_terminal if tail_terminal_visible else 0.0\n        )\n        exposed = direction * (exposed_second - exposed_first)\n        if exposed <= 0.5:\n            return min(exposed_first, exposed_second), 0.0\n        return min(exposed_first, exposed_second), exposed\n\n    @staticmethod\n    def _hold_shaft_height(\n        y1: float,\n        y2: float,\n        rendered_note_size: float,\n        *,\n        head_terminal_visible: bool,\n        tail_terminal_visible: bool,\n    ) -> float:\n        return GameplayPreviewWidget._hold_shaft_geometry(\n            y1,\n            y2,\n            rendered_note_size,\n            head_terminal_visible=head_terminal_visible,\n            tail_terminal_visible=tail_terminal_visible,\n        )[1]\n'''
assert old in text
text = text.replace(old, new, 1)

old = '''            shaft_height = self._hold_shaft_height(\n                y1,\n                y2,\n                rendered_note_size,\n                head_terminal_visible=head_visible,\n                tail_terminal_visible=tail_visible,\n            )\n            if shaft_height <= 0.0:\n                continue\n'''
new = '''            shaft_top, shaft_height = self._hold_shaft_geometry(\n                y1,\n                y2,\n                rendered_note_size,\n                head_terminal_visible=head_visible,\n                tail_terminal_visible=tail_visible,\n            )\n            if shaft_height <= 0.0:\n                continue\n'''
assert old in text
text = text.replace(old, new, 1)
text = text.replace('                min(y1, y2),\n                rendered_note_size,\n                shaft_height,\n', '                shaft_top,\n                rendered_note_size,\n                shaft_height,\n', 1)
text = text.replace('                            min(y1, y2),\n                            width,\n                            shaft_height,\n', '                            shaft_top,\n                            width,\n                            shaft_height,\n', 1)
preview.write_text(text, encoding='utf-8')


tests = Path('tests/unit/test_qt_preview.py')
text = tests.read_text(encoding='utf-8')
text = text.replace('import os\nimport unittest\n', 'import os\nimport unittest\nfrom pathlib import Path\nfrom types import SimpleNamespace\n', 1)
text = text.replace('    from PySide6.QtCore import QEvent, QPoint, QPointF, Qt\n', '    from PySide6.QtCore import QEvent, QPoint, QPointF, QRectF, Qt\n', 1)
text = text.replace('    from PySide6.QtGui import QImage, QKeyEvent, QPainter, QTransform\n', '    from PySide6.QtGui import QColor, QImage, QKeyEvent, QPainter, QPixmap, QTransform\n', 1)
text = text.replace('    from stepnx.codecs.nx20 import parse_bytes\n', '    from stepnx.authoring.noteskin import PngAtlas\n    from stepnx.codecs.nx20 import parse_bytes\n', 1)

old = '''            # If the head has already disappeared during an active sustain, a\n            # short real interval remains drawable instead of losing feedback.\n            self.assertEqual(\n                widget._hold_shaft_height(100.0, 110.0, size, head_terminal_visible=False, tail_terminal_visible=True),\n                10.0,\n            )\n'''
new = '''            # Once one endpoint disappears, trim only the terminal that is\n            # still visible. The exposed shaft begins at the hidden endpoint.\n            self.assertAlmostEqual(\n                widget._hold_shaft_height(\n                    100.0,\n                    100.0 + size / 2.0 + 10.0,\n                    size,\n                    head_terminal_visible=False,\n                    tail_terminal_visible=True,\n                ),\n                10.0,\n            )\n            top, exposed = widget._hold_shaft_geometry(\n                100.0,\n                100.0 + size + 12.0,\n                size,\n                head_terminal_visible=True,\n                tail_terminal_visible=True,\n            )\n            self.assertAlmostEqual(top, 100.0 + size / 2.0)\n            self.assertAlmostEqual(exposed, 12.0)\n'''
assert old in text
text = text.replace(old, new, 1)

needle = '    def test_collapsed_long_draws_head_after_tail_in_gameplay_preview(self) -> None:\n'
assert needle in text
new_test = '''    def test_gameplay_hold_terminals_clip_row_zero_to_the_native_shaft_strip(self) -> None:\n        widget = self._widget()\n        try:\n            atlas_image = QImage(480, 288, QImage.Format.Format_ARGB32)\n            atlas_image.fill(Qt.GlobalColor.transparent)\n            atlas_painter = QPainter(atlas_image)\n            try:\n                for column in range(5):\n                    x = column * 96\n                    atlas_painter.fillRect(QRectF(x, 0, 96, 8), QColor(\"#00ff00\"))\n                    atlas_painter.fillRect(\n                        QRectF(x, 96 + 20, 48, 31), QColor(\"#0000ff\")\n                    )\n                    atlas_painter.fillRect(\n                        QRectF(x + 48, 96 + 20, 48, 41), QColor(\"#0000ff\")\n                    )\n                    atlas_painter.fillRect(\n                        QRectF(x, 30, 48, 41), QColor(\"#ff00ff\")\n                    )\n                    atlas_painter.fillRect(\n                        QRectF(x + 48, 40, 48, 31), QColor(\"#ff00ff\")\n                    )\n            finally:\n                atlas_painter.end()\n\n            atlas = PngAtlas(Path(\"synthetic-hold.png\"), 5, 3)\n            bank = SimpleNamespace(animation=(atlas,))\n            widget._noteskin_pack = SimpleNamespace(\n                bank=lambda _subtype: bank,\n                item_animation=(),\n                division=None,\n            )\n            pixmap = QPixmap.fromImage(atlas_image)\n            source = widget.stream.events[0]\n            head = replace(\n                source,\n                lane=0,\n                raw=bytes((0x07, 0x03, source.raw[2], source.raw[3])),\n            )\n            tail = replace(\n                source,\n                lane=0,\n                raw=bytes((0x0F, 0x03, source.raw[2], source.raw[3])),\n            )\n\n            def render(note):\n                canvas = QImage(96, 96, QImage.Format.Format_ARGB32)\n                canvas.fill(Qt.GlobalColor.transparent)\n                painter = QPainter(canvas)\n                try:\n                    with patch.object(widget, \"_pixmap\", return_value=pixmap):\n                        self.assertTrue(\n                            widget._draw_asset(\n                                painter, note, QRectF(0.0, 0.0, 96.0, 96.0)\n                            )\n                        )\n                finally:\n                    painter.end()\n                return canvas\n\n            head_image = render(head)\n            tail_image = render(tail)\n            self.assertEqual(head_image.pixelColor(24, 50), QColor(\"#0000ff\"))\n            self.assertEqual(head_image.pixelColor(24, 51), QColor(\"#00ff00\"))\n            self.assertEqual(tail_image.pixelColor(24, 29), QColor(\"#00ff00\"))\n            self.assertEqual(tail_image.pixelColor(24, 30), QColor(\"#ff00ff\"))\n        finally:\n            widget.close()\n\n'''
text = text.replace(needle, new_test + needle, 1)
tests.write_text(text, encoding='utf-8')
